/**
 * Adapter for Conway Hall (conwayhall.org.uk).
 *
 * Each event card is a <conwayhall-event> element with a child
 * <script type="application/ld+json"> containing schema.org Event data.
 * This is much more reliable than scraping the card's visible markup — we
 * only fall back to hunting through the card's HTML for the one field the
 * JSON-LD omits: the event's own page URL.
 */

import * as cheerio from "cheerio";
import type { Event } from "../types";
import { parseLondonDateTime, stripHtml } from "../dates";

const LISTING_URL = "https://www.conwayhall.org.uk/whats-on/";
const SITE_ORIGIN = "https://www.conwayhall.org.uk";
const SOURCE_NAME = "Conway Hall";

// Auto-discovered by the aggregator's scrapers/ loader — must be exported
// by every adapter module.
export const name = SOURCE_NAME;

interface ConwayHallJsonLd {
  "@type"?: string;
  name?: string;
  startDate?: string;
  endDate?: string;
  description?: string;
}

export async function scrape(): Promise<Event[]> {
  const res = await fetch(LISTING_URL, {
    headers: { "User-Agent": "Mozilla/5.0 (compatible; EventAggregator/1.0)" },
  });

  if (!res.ok) {
    throw new Error(
      `Conway Hall listing returned ${res.status} ${res.statusText}`
    );
  }

  const html = await res.text();
  const $ = cheerio.load(html);
  const events: Event[] = [];

  $("conwayhall-event").each((_, el) => {
    try {
      const card = $(el);
      const script = card.find('script[type="application/ld+json"]').first();
      if (script.length === 0) return;

      const data = parseEventJsonLd(script.contents().text());
      if (!data) return;
      if (data["@type"] !== "Event" || !data.name || !data.startDate) return;

      const startDate = parseLondonDateTime(data.startDate);
      if (!startDate) return;

      const endDate = sanitizeEndDate(
        data.endDate ? parseLondonDateTime(data.endDate) : null,
        startDate,
        data.name
      );

      const url = findEventUrl(card);

      events.push({
        title: data.name.trim(),
        description: data.description
          ? stripHtml(data.description)
          : "A Conway Hall event.",
        startDate,
        endDate,
        url: url ?? LISTING_URL,
        source: SOURCE_NAME,
      });
    } catch {
      // isolate per-card failures; keep going
    }
  });

  return events;
}

/**
 * Conway Hall's JSON-LD is generated by a WordPress plugin that dumps rich
 * text (e.g. the `description` field) straight into the JSON string without
 * escaping it. When that source text has a trailing blank line, the emitted
 * JSON contains a raw, unescaped newline inside a quoted string — which is
 * invalid per the JSON spec and makes `JSON.parse` throw. Confirmed example:
 * the "Plot Twist: Harlan Coben and Bill Nighy" card's description ends
 * with a literal blank line before the closing quote.
 *
 * Rather than losing every event whose description happens to contain a
 * stray newline/tab, we walk the raw text and escape control characters
 * that fall *inside* a string literal (tracked via a simple quote-toggle
 * state machine — escaped quotes don't toggle it), leaving structural
 * whitespace between JSON tokens untouched.
 */
function parseEventJsonLd(raw: string): ConwayHallJsonLd | null {
  try {
    return JSON.parse(raw) as ConwayHallJsonLd;
  } catch {
    // fall through to the sanitizing pass below
  }

  let sanitized = "";
  let inString = false;
  let escapeNext = false;

  for (const char of raw) {
    if (escapeNext) {
      sanitized += char;
      escapeNext = false;
      continue;
    }
    if (char === "\\") {
      sanitized += char;
      escapeNext = true;
      continue;
    }
    if (char === '"') {
      inString = !inString;
      sanitized += char;
      continue;
    }
    if (inString && (char === "\n" || char === "\r" || char === "\t")) {
      sanitized +=
        char === "\n" ? "\\n" : char === "\r" ? "\\r" : "\\t";
      continue;
    }
    sanitized += char;
  }

  try {
    return JSON.parse(sanitized) as ConwayHallJsonLd;
  } catch (err) {
    console.warn(
      `Conway Hall: dropping one event — JSON-LD still invalid after sanitizing (${
        err instanceof Error ? err.message : String(err)
      })`
    );
    return null;
  }
}

/**
 * Confirmed data bug: at least one card's JSON-LD endDate lands on a
 * different day than its startDate/the human-readable <time> text agrees
 * on (e.g. start 22 Sept 19:00, JSON-LD end 30 Sept 20:30, but the visible
 * page says the event ends the same evening at 20:30). Rather than trust
 * an endDate that's implausibly far from its startDate, we drop it —
 * better to show no end time than a wrong one that spans over a week.
 */
const MAX_PLAUSIBLE_DURATION_MS = 24 * 60 * 60 * 1000;

function sanitizeEndDate(
  endDate: Date | null,
  startDate: Date,
  eventName: string
): Date | undefined {
  if (!endDate) return undefined;

  const durationMs = endDate.getTime() - startDate.getTime();
  if (durationMs < 0 || durationMs > MAX_PLAUSIBLE_DURATION_MS) {
    console.warn(
      `Conway Hall: discarding implausible endDate for "${eventName}" ` +
        `(start ${startDate.toISOString()}, end ${endDate.toISOString()})`
    );
    return undefined;
  }

  return endDate;
}

/**
 * The JSON-LD doesn't include a `url` field. Confirmed markup: each card
 * contains several <a href> tags — the thumbnail/title links point to the
 * event's own page (/whats-on/event/<slug>/), while a separate "Tickets"
 * button links off-site to conwayhall.ticketsolve.com. We explicitly match
 * the former rather than just taking the first <a>, so this doesn't break
 * if a future card ever orders its links differently.
 */
function findEventUrl(card: cheerio.Cheerio<any>): string | null {
  const eventPageLink = card
    .find('a[href*="/whats-on/event/"]')
    .first()
    .attr("href");

  if (eventPageLink) {
    return new URL(eventPageLink, SITE_ORIGIN).toString();
  }

  // Fall back to any in-page link if the URL pattern ever changes.
  const anyLink = card.find("a[href]").first().attr("href");
  return anyLink ? new URL(anyLink, SITE_ORIGIN).toString() : null;
}